### ISSUE TITLE
Workshops on EU CodeWeek

### ISSUE THREAD

**Issue by educodinglu** [codeeu/codeweek#1122]
Good morning,

I created an excel sheet to add over 100 workshops on the activity map of EU CodeWeek. I sent the excel file to Alain.VAN-DRIESSCHE@ext.ec.europa.eu.

I there are changes taht need to be done, please let me know.

Best regards

**Comment by alainvd** [comment]
Events have been imported and are live on the website.
Thanks for the listing.
