### ISSUE TITLE
Collaboration with Magenta Moon and Junge Tüftler

### ISSUE THREAD

**Issue by AlexaBoe** [codeeu/codeweek#1141]
Dear Code Week team,

Junge Tüftler and other initiatives at Magenta Moon in Berlin would like to communicate their events vie the Europe Code Week Website. We weren't sure how to include the images in the excel sheet and added accessible Google Drive links. Please let us know if the images are not accessible for you or the website. 
Thanks a lot!

[events_junge tueftler.xlsx](https://github.com/codeeu/codeweek/files/5385324/events_junge.tueftler.xlsx)

**Comment by alainvd** [comment]
Hi,

Thanks for the excel file. The activities have been imported.
I copied the images on codeweek resources so that is easier for us and you don't have to keep those files available.

Sample activity: https://codeweek.eu/view/330539/melodische-mondpflanzen-mit-makey-makey

Kind regards,
Alain.
