### ISSUE TITLE
Inconsistancy at action event response 

### ISSUE THREAD

**Issue by ioana-chiorean** [codeeu/codeweek#1441]
Steps:
- Approve or reject an event
- check the message u receive 
Expected 
- message is consistent in lower or capitals structure, or camel case, etc. 
Actual:
- the success is in low letters and the rest is written with capitals for each word. 

![Screenshot 2021-05-19 at 13 12 25 (2)](https://user-images.githubusercontent.com/1391451/118810972-c097ed80-b8ac-11eb-84a0-edc860839168.png)
![Screenshot 2021-05-19 at 13 10 10 (2)](https://user-images.githubusercontent.com/1391451/118810986-c42b7480-b8ac-11eb-8fae-de4607e87ed8.png)

**Comment by alainvd** [comment]
This has been fixed.
