### ISSUE TITLE
Bug - No pending events message when there are still pending.

### ISSUE THREAD

**Issue by ioana-chiorean** [codeeu/codeweek#1442]
Steps:
- have 2 pages of events. 
- approve/reject all of them from that page ( not the first one)

Expected:
- you should have been moved to page 1 of events

Actual 
- you get the message that there are no other pending events under the initial message that there are other 6 pending events. 
- the copy is also ambiguous see #1443

![Screenshot 2021-05-19 at 13 09 09](https://user-images.githubusercontent.com/1391451/118812057-030dfa00-b8ae-11eb-9cb8-d3abf19602ad.png)

**Comment by alainvd** [comment]
Hi,

The bug has been removed and it is not possible to go to a page that has no pending activities anymore.

Thanks,
Alain.
