### ISSUE TITLE
Improvement - Ambiguous copy 

### ISSUE THREAD

**Issue by ioana-chiorean** [codeeu/codeweek#1443]
Steps:
- Approve or Reject all events from a page;

The message "No Pending Activity found for countries" is bogus:
- which countries? Mine? All? 
- No Pending Activity is in Capitals but should no be. 

![Screenshot 2021-05-19 at 13 09 02](https://user-images.githubusercontent.com/1391451/118812277-394b7980-b8ae-11eb-8e2a-36e4bea9a21d.png)

**Comment by alainvd** [comment]
This has been fixed.

Alain.
