### ISSUE TITLE
Reporting suggestions CW22

### ISSUE THREAD

**Issue by moorlag** [codeeu/codeweek#1651]
- [ ] The overview on [CodeWeek Reporting](https://codeweek.eu/events_to_report) is not showing reported activities once reported. It could be made clear that activity report certificates can be found under the activity overview. 

- [ ] The incentive to report every activity has a lot of potential. The data in the reporting is very valuable. Perhaps we can recognize the top 3 countries with the most reported activities. 

- [ ] As for similar activities in more than one school - more than one class; it would help to customize the certificates afterward. So every contributing school can receive a certificate.

**Comment by alainvd** [comment]
This is a great feedback.
I reckon we could have more clarity about the status of the reports per user.

Do you think the reporting leaderboard should also be public ? or would it create confusion ? 
Or should we mix it in a clever way with the scoreboard numbers ?

**Comment by moorlag** [comment]
Leaderboards are always great. Sharing the reported activities with leaders via email would be preferable. It's not a leadership position that is 'newsworthy' for non-contributors. The current leaderboard is already a bit confusing. It's filled with user-generated content, and it's filled with a diverse feed (calenders from all over the world). That would be a separate issue; what's the value of being on top? What's the value of a 'rising star'?
