### ISSUE TITLE
Text missing or vissible from the send/reject button

### ISSUE THREAD

**Issue by ioana-chiorean** [codeeu/codeweek#1747]
Go to an event - press reject 
the pop-up message has the border for text input slightly visible and the button to submit the text has no text or invisible at this point. 

<img width="781" alt="Screenshot 2022-03-31 at 07 22 18" src="https://user-images.githubusercontent.com/1391451/160982461-216729bc-d296-4a87-8dc6-178acecb09fc.png">

**Comment by ioana-chiorean** [comment]
At hovering over the button the text on cancel get highlighted but nothing happens for the second button
<img width="785" alt="Screenshot 2022-03-31 at 07 26 12" src="https://user-images.githubusercontent.com/1391451/160982750-c672a05b-3f67-4bf7-b733-794a1d5656a6.png">

**Comment by alainvd** [comment]
Colors have been changed and the buttons are visible again.
this happened because we upgraded the Tailwind library from v1 to v2 a few weeks ago.
