### ISSUE TITLE
CodeWeek activities CoderDojo Belgium

### ISSUE THREAD

**Issue by CindySmits** [codeeu/codeweek#1885]
[events.xlsx](https://github.com/codeeu/codeweek/files/9686136/events.xlsx)

**Comment by alainvd** [comment]
@CindySmits 

- can you tell me which picture to use as the current link is the linkedin page, not a logo
- The latitude and longitude is missing. Can you please add them ?

**Comment by CindySmits** [comment]
Hello,

Attached the list with coordinates and also a logo.

Regards,
Cindy


On 3 October 2022 at 16:41:23, alainvd ***@***.***) wrote:

@CindySmits

can you tell me which picture to use as the current link is the linkedin page, not a logo
The latitude and longitude is missing. Can you please add them ?

**Comment by alainvd** [comment]
Hi Cindy,

I don't see any attachment :/

**Comment by CindySmits** [comment]
Oeps - one more try..


On 7 October 2022 at 09:02:13, alainvd ***@***.***) wrote:

Hi Cindy,

I don't see any attachment :/
