### ISSUE TITLE
<Romanian L10n>  missing translations in menu & event triage/review

### ISSUE THREAD

**Issue by ioana-chiorean** [codeeu/codeweek#1933]
Changing to RO L10n you can see still some EN labels/buttons:

Menu:
- Activities Locations = Locul activitățiilor
- Online Activities = Activități online

Activities in pending - nr 6 in this case 
-Activities =Activități 

Buttons:
- Approve = Aprobă
- Reject = Respinge
- Delete =  Șterge

@alainvd I am checking now if i can propose some PRs for them

<img width="1221" alt="Screenshot 2022-10-13 at 14 17 01" src="https://user-images.githubusercontent.com/1391451/195594381-9be1d1eb-b973-469e-9c6b-66fa89cbe5a8.png">

**Comment by ioana-chiorean** [comment]
Checked with others languages and it seems it is not translated either ( Spanish for ex) 
I think we need to implemented the pages in all anguages

**Comment by alainvd** [comment]
Hi,

As it is not a public page, it is not translated in all languages. Only english and romanian so far.
We can ask ambassadors to translate it if they feel the need.
