### ISSUE TITLE
Website Font compatibility and Fallback

### ISSUE THREAD

**Issue by mixasgr** [codeeu/codeweek#1951]
Hello Codeweek team!

I am opening this issue, as an enhancement request in regards to the used font.
I stumbled upon the issue at the greek translation of the website. It seems that "PT Sans" that is currently used is not compatible with/does not support Greek characters. This could also be the case for characters in other languages.

This results in that browsers render the Greek characters based on their local settings for the default font which differs depending the used Operating System, Browser and other local settings.

For example Firefox usually uses "Times New Roman" as the default on Windows systems, "Times" on MacOs and "Dejavu Serif" on Linux distros like "Linux Mint". So the greek version of the website seems different from other languages and also is different for every user based on their device.

Moreover some of the default browser fonts seems to "break" or not be compatible with the website UI. For example on Firefox/Linux Mint, the website loads as at the following images:

**1)Main Page**
\-------------------------------------------------------------------
![codeweek_eu-font-1](https://user-images.githubusercontent.com/16108484/197498816-dfc01d5a-d19d-45ea-8557-df6cb8b1e553.jpg)
\-------------------------------------------------------------------

**2)Participation Page**
\-------------------------------------------------------------------
![codeweek_eu-font-2](https://user-images.githubusercontent.com/16108484/197498942-c20e0b75-27d2-4d64-b5df-013984101ec0.jpg)
\-------------------------------------------------------------------

**3)Challenges Page**
\-------------------------------------------------------------------
![codeweek_eu-font-3](https://user-images.githubusercontent.com/16108484/197499059-d3ba6b01-0542-4022-8548-bade271f7249.jpg)
\-------------------------------------------------------------------

As you can see the text, eg at the menu is overlapping and in general the content is "bulky" or not fitting the UI.

Based on the above,  i would like to request for the use of an other compatible font. As this could be probably more difficult to implement, as an alternative you could add a fallback web font, eg Roboto, that could be loaded in case characters are not compatible with "PT Sans".

For example, testing with "Roboto" ("font-family: PT Sans, Roboto;") produces a more compatible and similar to other languages UI:

**4)Main Page**
\-------------------------------------------------------------------
![codeweek_eu-font-4](https://user-images.githubusercontent.com/16108484/197499804-5225269d-ee7f-4598-97c5-71de75d38913.jpg)
 \-------------------------------------------------------------------

**5)Participation Page**
\-------------------------------------------------------------------
![codeweek_eu-font-6](https://user-images.githubusercontent.com/16108484/197502700-9be41744-b2db-430f-a80d-4245fea6ef3f.jpg)
\-------------------------------------------------------------------

**6)Challenges Page**
\-------------------------------------------------------------------
![codeweek_eu-font-5](https://user-images.githubusercontent.com/16108484/197500717-6e34b00d-03ec-480c-abe7-d7e448b18447.jpg)
\-------------------------------------------------------------------

Thank you!

**Comment by alainvd** [comment]
Thanks for the ticket. Roboto has been added as a fallbacl. Please let me know if it is better for you.

**Comment by mixasgr** [comment]
> Thanks for the ticket. Roboto has been added as a fallbacl. Please let me know if it is better for you.

Thank you! everything seems fine!
