### ISSUE TITLE
IT event under RO

### ISSUE THREAD

**Issue by ioana-chiorean** [codeeu/codeweek#1974]
https://codeweek.eu/view/503707/programma-senti-impara 

I approve it as I do understand IT but was under our review list.

**Comment by alainvd** [comment]
the address is via Giuseppe Silla 3
and the service used to map the address to countries guessed it was romania.
Can't blame him too much as the address is not really precise and does not contain the country.

**Comment by ioana-chiorean** [comment]
Indeed but i did not expect it to have a Giuseppe Address in RO :))
