### ISSUE TITLE
Perf. investigation - 504 

### ISSUE THREAD

**Issue by ioana-chiorean** [codeeu/codeweek#1976]
Got this several times during this event - maybe worth investigating? 
<img width="1699" alt="Screenshot 2022-10-27 at 23 22 55" src="https://user-images.githubusercontent.com/1391451/198401993-795ec629-55a4-4dd8-a418-009a26bf92f5.png">

**Comment by alainvd** [comment]
504 were thrown because the side was really busy. Please let me know if this happens again.
Thanks

**Comment by ioana-chiorean** [comment]
If we know about it - it is fine - thanks fro checking!
