### ISSUE TITLE
Social preview not loading

### ISSUE THREAD

**Issue by moorlag** [codeeu/codeweek#2020]
Not all pages in the domain show a social preview. 
The preview helps to convert impressions to visitors. 
WP has a few plugins that support this action. [Yoast is one of the favorites](https://yoast.com/features/content-previews/social-previews/)

https://codeweek.eu/resources/CodingAtHome/right-and-left

![Scherm­afbeelding 2022-12-09 om 10 19 04](https://user-images.githubusercontent.com/2832006/206668156-c3a0e930-0320-452d-bd67-99f26e149c53.png)

**Comment by alainvd** [comment]
Good suggestion, thanks !
Unfortunately we are not using Wordpress and can't use Yoast out of the box.
