### ISSUE TITLE
Can't add event

### ISSUE THREAD

**Issue by alainvd** [codeeu/codeweek#289]
I have problems adding an event to the website. Although I have filled in all required fields, clicking Add event just gives me a pop-up saying "School location is required"
![no-map](https://user-images.githubusercontent.com/3462620/54741174-e090d100-4bbd-11e9-8c04-b5fad23d3e25.jpg)

**Comment by softfrontier** [comment]
As you can see from the screenshot, the map did not load.
I retried later, and then the map loaded and I was able to add the event without the error message.
At the time when the map did not load, I had a notification that AdBlock blocked and ad on the site.
When the map did load, that notification was gone.

**Comment by alainvd** [comment]
Appears to be linked with adblock. After a refresh it worked so I'll close this issue.
