### ISSUE TITLE
Check language for all pages and redirect

### ISSUE THREAD

**Issue by alainvd** [codeeu/codeweek#357]
Allow any page to be linked with a language code

**Comment by alainvd** [comment]
The language detection is active on codeweek.eu.

Now, you can share links with an additional parameter named ‘lang’ and the language will be set automatically.

For example, to link the training modules in Spanish, you can use the following URL:
https://codeweek.eu/training?lang=es

This extra parameter works on all the pages.

The full list of languages codes is the following:
Albanese: al
Bosnian: ba
Bulgarian: bg
Croatian: hr
Czech: cs
Danish: da
Dutch: nl
English: en
Estonian: et
Finnish: fi
French: fr
German: de
Greek: el
Hungarian: hu
Italian: it
Latvian: lv
Lithuanian: lt
Macedonian: mk
Maltese: mt
Montenegrin: me
Polish: pl
Portuguese: pt
Romanian: ro
Serbian: rs
Slovak: sk
Slovenian: sl
Spanish: es
Swedish: sv
Turkish: tr

Those codes are case insensitive so you can use lowercase or uppercase language code.

**Comment by ioana-chiorean** [comment]
🙌
