### ISSUE TITLE
Sponsors cleanup

### ISSUE THREAD

**Issue by angeliquevd** [codeeu/codeweek#57]
Please delete the following sponsor logos and add University of Urbino (see link belw).

•         Neunet 
•         ICT in Practice 
•         Lego Education? 
•         SAP –
•         Stifter Helfen – 
•         European Tech Alliance 
![logo_uniurb](https://user-images.githubusercontent.com/3462620/46217865-72bcc880-c343-11e8-9d81-8138547769c2.png)

**Comment by alainvd** [comment]
http://mooc.uniurb.it/codeweekmooc/

**Comment by alainvd** [comment]
https://mooc.uniurb.it/wp/codeweekmooc/
