### ISSUE TITLE
Limit description of activities in overview 

### ISSUE THREAD

**Issue by sp4c31nv4d3r** [codeeu/codeweek#573]
Currently, the description of activities on the events overview is shown in full, leading to very long blocks and long scrolling. Limiting them to 4-5 lines would lead to a better and quicker overview.

**Comment by alainvd** [comment]
This was the case before. I suppose it is a regression that came with the re-design.
Thanks for letting us know.

**Comment by alainvd** [comment]
Limit set to 200 characters now
