### ISSUE TITLE
event detail page breaks layout

### ISSUE THREAD

**Issue by Grienauer** [codeeu/codeweek#629]
the responsive view could be improved.
![Bildschirmfoto 2019-10-14 um 21 25 28](https://user-images.githubusercontent.com/1458107/66777470-64e3d200-eec9-11e9-9422-049cc330e080.png)
the calendar should move down under the next element to not break the layout.

possible solution:
add missing flex wrap to element.
`
.codeweek-form-inner-two-columns {
    flex-wrap: wrap;
}
`

**Comment by alainvd** [comment]
It should be better on mobile now.
The calendar widget is hidden for smaller resolution.
