### ISSUE TITLE
Image not appearing on event

### ISSUE THREAD

**Issue by softfrontier** [codeeu/codeweek#85]
Hello,

I try to upload the attached image to my event, but it does not appear on the event.

I get no error message, it is just that the image is not uploaded and the default code week image is shown on the event.
![robotter](https://user-images.githubusercontent.com/5276394/46456181-48896180-c7ae-11e8-9b04-ba3d70e31c20.jpg)

**Comment by alainvd** [comment]
Hi @softfrontier 
Can you please give me the event ID so I can have a look in the database ?
Thanks :)

**Comment by alainvd** [comment]
No further comment so I close
