### ISSUE TITLE
Options in "Who is the activity for?" not readable when adding new event

### ISSUE THREAD

**Issue by synolus-david** [codeeu/codeweek#919]
Hi guys,

I just wanted to tell you that when you add a new event here: https://codeweek.eu/add you are not able to read the options in the section "Who is the activity for?". Guess it is a color problem. 

Great work anyways - all the best!

David

**Comment by alainvd** [comment]
Hi David,

Thanks for the notification. It was a small glitch that is now fixed.

Thanks again,
Alain.
