### ISSUE TITLE
Show type of event in event

### ISSUE THREAD

**Issue by sp4c31nv4d3r** [codeeu/codeweek#928]
On the map, one can filter for "type of event". This however is not shown in the event itself. 

Problem:
Just browsing events on the map could lead to find an interesting activity, but one wouldn't know if it's online or open for all. In order to do that, they have to set the filters and hope to find it again.

Solution:
In an event, that information could be visible right underneath the other filters (audience, topic and tags).

**Comment by alainvd** [comment]
Good idea. We'll add this information soon as it makes sense to include it.

Thanks !

**Comment by alainvd** [comment]
The activity type is now visible in the activity details page.
