### ISSUE TITLE
Meet and Code API Bug

### ISSUE THREAD

**Issue by sp4c31nv4d3r** [codeeu/codeweek#981]
Aparently, events created via Meet & Code show up as an event at our site, but without the mandatory fields "This activity is for: " and "Main themes: ". I don't know if this is connected, but worse: The description stops after 2 lines, making most descriptions unreadable.

Workaround: Me, editing the event - copying the full text from the Meet & Code website, adding the tags if I can read them from the description. I can't do this for all events though.

Suggestion: Automatic addition of "other" for the mandatory fields. Hoping that helps with the description as well? Maybe it's another error alltogether - Maybe the transfer is wrong in one place and description and those 2 fields are simply not transmitted at all.

**Comment by alainvd** [comment]
Hi,

I have seen the problem and I'm working on it.
I'll also try to update automatically the ones that are already on codeweek with a shorter description.
I'll keep you updated.

**Comment by alainvd** [comment]
Bug has been hunted and squashed.
All the meetandcode events have been updated with the right full length description so you don't have to go through all the events manually ;-)

Cheers.
